### ISSUE TITLE
Going to homepage on redirect from gateway

### ISSUE THREAD

**Issue by ioweb-gr** [Cardlink-SA/cardlink-checkout-magento-v2#1]
When returning from the payment gateway, the user is redirected to the homepage on magento 2.4.6-p4 

The problem is in the missing implementation for `HttpPostActionInterface / CsrfAwareInterface` in `\Cardlink\Checkout\Controller\Payment\Response`

**Comment by dimosKougiou** [comment]
You can read our documentation at our updated README file
